In [4]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

In [5]:
df.head() #give us top 5 rows

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [6]:
df.info() #but just looking at the data is not enough, so use .info

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [7]:
df.describe(include = 'all') # to check summary statistics of numerical column but use all to show all

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [8]:
#check missing values
df.isnull().sum() #we see that review rating has 37 nulls, what do we do about that, fill with mean/median

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
 #we saw review rating has 37 nulls, what do we do about that, replace null with mean/median
#we genarally would choose median over mean beacuse mean can eb affected by outliers, and not median, but we can't fill all rating with median of 
#entire column and move on, yes it can work but its not the best practice, beacuse rating can vary a lot based on category
#we will find a median rating for each acatgeory and replace each null by its real category median
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [10]:
df.isnull().sum() #check if we have any nulls now, and we don't

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
# Renaming columns according to snake casing for better readability and documentation - otherwise you'd have to remember exactly how they are
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [12]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [13]:
#create a new column for age group
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels=labels)

In [14]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [15]:
# create new column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [16]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [17]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [18]:
#check if the 2 columns conatin the same info
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [20]:
# Dropping promo code used column

df = df.drop('promo_code_used', axis=1)

KeyError: "['promo_code_used'] not found in axis"

In [21]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [23]:
!pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\mpume\appdata\local\programs\python\python313\lib\site-packages (2.0.44)
Requirement already satisfied: greenlet>=1 in c:\users\mpume\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\mpume\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 689.1 kB/s eta 0:00:04
   ----------- ---------------------------- 0.8/2.8 MB 1.1 MB/s eta 0:00:02
   ----------- ---------------------------- 0.8/2.8 MB 1.1 MB/s eta 0:00:02
   ------------------- -------------------- 1.3/2.8 MB 1.1 MB/s eta 0:00:02
   ------------------- -------------------- 1.3/2.8 MB 1.1 MB/s eta 0:00:02
   ------------------- -------------------- 1.3/2.8 MB 1.1 MB/s eta 0:00:02
   -------------------------- ------------- 1.8/2.8 MB 1.1 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.8 MB 993.2 kB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.8 MB 993.2 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 941.5 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 941.5 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.8 MB 941.9 kB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 892.6 kB/s  0:00:03
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\mpume\appdata\local\programs\python\python313\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\mpume\appdata\local\programs\python\python313\lib\site-packages (2.0.44)
Requirement already satisfied: greenlet>=1 in c:\users\mpume\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\mpume\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
!pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\users\mpume\appdata\local\programs\python\python313\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\mpume\appdata\local\programs\python\python313\lib\site-packages (2.0.44)
Requirement already satisfied: greenlet>=1 in c:\users\mpume\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\mpume\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
from sqlalchemy import create_engine
import pandas as pd

# SQL Server connection with Windows Authentication
engine = create_engine('mssql+pyodbc://@localhost/Customer Behavior?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes')

# Write DataFrame to SQL Server
table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT TOP 5 * FROM customer;", engine)

C:\Users\mpume\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\sql.py:1649: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [32]:
pd.read_sql("sp_columns customer;", engine)

,TABLE_QUALIFIER,TABLE_OWNER,TABLE_NAME,COLUMN_NAME,DATA_TYPE,TYPE_NAME,PRECISION,LENGTH,SCALE,RADIX,NULLABLE,REMARKS,COLUMN_DEF,SQL_DATA_TYPE,SQL_DATETIME_SUB,CHAR_OCTET_LENGTH,ORDINAL_POSITION,IS_NULLABLE,SS_DATA_TYPE
0,Customer Behavior,dbo,customer,customer_id,-5,bigint,19,8,0.0,10.0,1,None,None,-5,None,NaN,1,YES,108
1,Customer Behavior,dbo,customer,age,-5,bigint,19,8,0.0,10.0,1,None,None,-5,None,NaN,2,YES,108
2,Customer Behavior,dbo,customer,gender,-1,text,2147483647,2147483647,NaN,NaN,1,None,None,-1,None,2.147484e+09,3,YES,39
3,Customer Behavior,dbo,customer,item_purchased,-1,text,2147483647,2147483647,NaN,NaN,1,None,None,-1,None,2.147484e+09,4,YES,39
4,Customer Behavior,dbo,customer,category,-1,text,2147483647,2147483647,NaN,NaN,1,None,None,-1,None,2.147484e+09,5,YES,39
5,Customer Behavior,dbo,customer,purchase_amount,-5,bigint,19,8,0.0,10.0,1,None,None,-5,None,NaN,6,YES,108
6,Customer Behavior,dbo,customer,location,-1,text,2147483647,2147483647,NaN,NaN,1,None,None,-1,None,2.147484e+09,7,YES,39
7,Customer Behavior,dbo,customer,size,-1,text,2147483647,2147483647,NaN,NaN,1,None,None,-1,None,2.147484e+09,8,YES,39
8,Customer Behavior,dbo,customer,color,-1,text,2147483647,2147483647,NaN,NaN,1,None,None,-1,None,2.147484e+09,9,YES,39
9,Customer Behavior,dbo,customer,season,-1,text,2147483647,2147483647,NaN,NaN,1,None,None,-1,None,2.147484e+09,10,YES,39
10,Customer Behavior,dbo,customer,review_rating,6,float,15,8,NaN,10.0,1,None,None,6,None,NaN,11,YES,109
11,Customer Behavior,dbo,customer,subscription_status,-1,text,2147483647,2147483647,NaN,NaN,1,None,None,-1,None,2.147484e+09,12,YES,39
12,Customer Behavior,dbo,customer,shipping_type,-1,text,2147483647,2147483647,NaN,NaN,1,None,None,-1,None,2.147484e+09,13,YES,39
13,Customer Behavior,dbo,customer,discount_applied,-1,text,2147483647,2147483647,NaN,NaN,1,None,None,-1,None,2.147484e+09,14,YES,39
14,Customer Behavior,dbo,customer,previous_purchases,-5,bigint,19,8,0.0,10.0,1,None,None,-5,None,NaN,15,YES,108
15,Customer Behavior,dbo,customer,payment_method,-1,text,2147483647,2147483647,NaN,NaN,1,None,None,-1,None,2.147484e+09,16,YES,39
16,Customer Behavior,dbo,customer,frequency_of_purchases,-1,text,2147483647,2147483647,NaN,NaN,1,None,None,-1,None,2.147484e+09,17,YES,39
17,Customer Behavior,dbo,customer,age_group,-1,text,2147483647,2147483647,NaN,NaN,1,None,None,-1,None,2.147484e+09,18,YES,39
18,Customer Behavior,dbo,customer,purchase_frequency_days,-5,bigint,19,8,0.0,10.0,1,None,None,-5,None,NaN,19,YES,108